from enum import Enum

class FSMState(str, Enum):
    IDLE = "IDLE"
    SELECTING_SPECIALTY = "SELECTING_SPECIALTY"
    SELECTING_DOCTOR = "SELECTING_DOCTOR"
    SELECTING_TIME = "SELECTING_TIME"
    CONFIRMING_BOOKING = "CONFIRMING_BOOKING"
    CANCELLING_BOOKING = "CANCELLING_BOOKING"
    RESCHEDULING_BOOKING = "RESCHEDULING_BOOKING"
    VIEWING_BOOKINGS = "VIEWING_BOOKINGS"
    UPDATING_PROFILE = "UPDATING_PROFILE"
    WAITING_FAQ = "WAITING_FAQ"
    JOINING_WAITLIST = "JOINING_WAITLIST"
    VIEWING_REPORT = "VIEWING_REPORT"

class Intent(str, Enum):
    BOOK_APPOINTMENT = "BOOK_APPOINTMENT"
    MY_BOOKINGS = "MY_BOOKINGS"
    CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT"
    RESCHEDULE_APPOINTMENT = "RESCHEDULE_APPOINTMENT"
    GET_REPORT = "GET_REPORT"
    MANAGE_REMINDERS = "MANAGE_REMINDERS"
    GET_INFO = "GET_INFO"
    MANAGE_PROFILE = "MANAGE_PROFILE"
    UNKNOWN = "UNKNOWN"

class BookingStatus(str, Enum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
