summary: ''
description: ''
lock: '!inline f/internal/fsm_router/handlers/_smart_prefill_handler.script.lock'
kind: script
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties: {}
  required: []
